### PR TITLE
Update et1x000.conf

### PR DESCRIPTION
**Pull request by Dima73**
add missing KERNEL_FILE = "kernel.bin" 
next name zImage???

### CODE REVIEW

**Comment by neo-pli-bsps** [comment]
Why is this needed, it always worked before?

**Comment by Dima73** [comment]
The ofgwrite utility does not understand if the kernel file is called zImage and not kernel.bin.
screen

**Comment by Dima73** [comment]
Openpli 7.3 https://github.com/neo-pli-bsps/meta-gi/blob/70a33b8de903f26d9d9e47690854e740dd56fe42/conf/machine/include/et1x000.inc

**Comment by betacentauri** [comment]
Yes, Dimitrij is right. At the moment ofgwrite cannot handle zImage kernel files. And also e2 would need to be adapted:
https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Screens/FlashImage.py#L23

So can you please merge?

**Pull request merged**
